name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Telegram Bot Docker Image
      run: docker build -t my-telegram-bot .

    - name: Deploy Telegram Bot Container
      run: |
        docker stop my-telegram-bot || true
        docker rm my-telegram-bot || true
        docker run -d --name my-telegram-bot \
          -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          -e WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} \
          -v ${{ secrets.DB_PATH }}/db:/app/db \
          -p 8000:8000 my-telegram-bot
